

DELETE http://localhost:3003/api/blogs/5f84b54b2855b240724a453e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmODRiMzU5OWY2NWVkM2YyMmRjNzcxZiIsImlhdCI6MTYwMjUzMjcwMX0.pXqfoai5KV_A_AWgZNsbhKvB2Xso8QzI8oT_aboKedI