POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmODRiMzU5OWY2NWVkM2YyMmRjNzcxZiIsImlhdCI6MTYwMjUzMjQ3Mn0.wLeqx0KZ0hIoEq7slPYGjViPY4W1pivs0PvhKVOmFxc

{
    "title": "blog post to test deleting blogs w tokens",
    "author": "Root",
    "url": "https://xyz.com",
    "likes": 100
}