POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "placeholder blog post 3",
    "author" : "Anirudh also",
    "url" : "www.placeholder.com/blog3",
    "likes" : 9

}